### ISSUE TITLE
No Reachable Points Despite Visibly Reachable Targets in RViz

### ISSUE THREAD

**Issue by Mahatrs** [ros-industrial/reach_ros2#42]
Hello,
I'm running a reachability study with REACH ROS2 using the KUKA LBR iiwa14 URDF ([link to repo](https://github.com/lbr-stack/lbr_fri_ros2_stack/tree/humble/lbr_description/urdf/iiwa14)) with a tool added to the end-effector. In RViz, many of the target points clearly appear reachable, but REACH reports zero reachable points.
- I believe my TCP frame is correct: the Z-axis points “out” of the tool and direct opposite orientation of the normal vectors shown in the point cloud visualization.
- For the point cloud, the `pcl_mesh_sampling` command didn’t work, so I converted the mesh to a point cloud using a third-party tool.

Are there any known issues or additional checks I can perform when the TCP appears correct and targets are visibly reachable, but no solutions are found?

Thanks again — I’d appreciate any guidance!

Here's my configuration file : 
```
# Anchors
planning_group: &planning_group arm
collision_mesh_filename: &collision_mesh_filename package://reach_ros/demo/config/sw1_table.PLY

optimization:
  radius: 0.2
  max_steps: 10
  step_improvement_threshold: 0.01

ik_solver:
  name: MoveItIKSolver
  distance_threshold: 0.2
  planning_group: *planning_group
  collision_mesh_filename: *collision_mesh_filename
  touch_links: [lbr_link_ee]

evaluator:
  name: MultiplicativeEvaluator
  plugins:
    - name: ManipulabilityMoveIt
      planning_group: *planning_group
    - name: DistancePenaltyMoveIt
      planning_group: *planning_group
      distance_threshold: 0.1
      exponent: 2
      collision_mesh_filename: *collision_mesh_filename
      touch_links: [lbr_link_ee]

display:
  name: ROSDisplay
  collision_mesh_filename: *collision_mesh_filename
  kinematic_base_frame: lbr_link_0
  marker_scale: 0.1
  use_full_color_range: true
target_pose_generator:
  name: PointCloudTargetPoseGenerator
  pcd_file: package://reach_ros/demo/config/sw5_front.pcd
  points_frame: lbr_link_0
  target_frame: lbr_link_0

logger:
  name: BoostProgressConsoleLogger
```
Here's the added tool in the iiwa14 xacro file : 

```
       <joint name="${robot_name}_joint_ee" type="fixed">
            <parent link="${robot_name}_link_7" />
            <child link="${robot_name}_link_ee" />
            <origin xyz="0 0 0.035" rpy="0 0 0" />
        </joint>

        <link name="${robot_name}_link_ee">
            <inertial>
              <origin rpy="0 0 0" xyz="0 0 0.1" />
              <mass value="0.5"/>
              <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
            </inertial>
            <visual>
      	       <origin xyz="0 0 0" rpy="0 0 0" />
               <geometry>
                 <mesh filename="package://lbr_description/meshes/iiwa14/visual/end_eff.dae" scale="0.001 0.001 0.001"/>
               </geometry>
               <material name="gray">
               	  <color rgba="0.5 0.5 0.5 1"/>
      	       </material>
            </visual>
            <collision>
              <origin xyz="0 0 0" rpy="0 0 0" />
              <geometry>
                <mesh filename="package://lbr_description/meshes/iiwa14/collision/end_eff.stl" scale="0.001 0.001 0.001"/>
              </geometry>
            </collision>
        </link>

```
Here's a visualization in Rviz : 

![Image](https://github.com/user-attachments/assets/dfe05216-6133-4851-b009-f4b500c5203f)

![Image](https://github.com/user-attachments/assets/cd694bba-2397-407d-9129-a1eeb980b222)
